### ISSUE TITLE
Hidden error

### ISSUE THREAD

**Issue by fredrikw** [andreax79/python-sharepoint-cli#2]
Thank you for providing this tool, it's really useful to me since I didn't manage to set up O365 properly. However, I got a problem with the configure command (see pull request #1 ) and while trouble shooting I had some problem with the following lines. They are swollowing the helpful error message that the configure-section was missing in an unhelpful return code. Since it is a design question, I don't have a suggestion on how to improve the reporting, but I think it would be good to do so somehow. In my copy, I simply removed the except clause to send the exception to the terminal but I suppose that isn't very user friendly...

https://github.com/andreax79/python-sharepoint-cli/blob/887aae527dc0c599adfdc76d7fa593e04777b432/sharepointcli/cli.py#L129-L130

**Comment by andreax79** [comment]
Fixed in version 2.1.0
